import { Euler, Vector3 } from "three";

export const device = {
    desktop: {
        start: new Vector3(0, 1.6, -0.2),
        zoom: new Vector3(-2, 8, 2),
        second: new Vector3(0, 1.6, 1.5),
        third: new Vector3(0, 2, 2.5),
        end: new Vector3(0, 3, 8),
        startAngle: new Euler(0, 0, 0),
        secondAngle: new Euler(0, 0, 0),
        thirdAngle: new Euler(-Math.PI / 9, 0, 0),
        zoomAngle: new Euler(-Math.PI / 2, 0, 0),
        endAngle: new Euler(-Math.PI / 7, 0, 0),
    },
    tablet: {
        start: new Vector3(-2, 0.7, -0.1),
        zoom: new Vector3(-2, 12, 2),
        second: new Vector3(-1.75, 1.25, 0),
        third: new Vector3(-1, 3, 2),
        end: new Vector3(0, 3, 8),
        startAngle: new Euler(-Math.PI / 2, 0, Math.PI / 40),
        secondAngle: new Euler(-Math.PI / 2, 0, Math.PI / 40),
        thirdAngle: new Euler(-Math.PI / 5, 0, 0),
        zoomAngle: new Euler(-Math.PI / 2, 0, 0),
        endAngle: new Euler(-Math.PI / 7, 0, 0),
    },
    mobile: {
        start: new Vector3(-0.25, 0.2, -0.25),
        zoom: new Vector3(-1, 16, 3),
        second: new Vector3(-0.25, 1, -0.25),
        third: new Vector3(0, 3, 2),
        end: new Vector3(0, 3, 8),
        startAngle: new Euler(-Math.PI / 2, 0, 0),
        secondAngle: new Euler(-Math.PI / 2, 0, 0),
        thirdAngle: new Euler(-Math.PI / 5, 0, 0),
        zoomAngle: new Euler(-Math.PI / 2, 0, 0),
        endAngle: new Euler(-Math.PI / 7, 0, 0),
    },
} as const;
